"""Initial database migration for user profile records."""

# Generated by Django 6.0.6 on 2026-07-06 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('organization', models.CharField(blank=True, help_text='Club, academy, school, or company name.', max_length=150)),
                ('sport_role', models.CharField(choices=[('coach', 'Coach'), ('player', 'Player'), ('scout', 'Scout'), ('analyst', 'Analyst'), ('other', 'Other')], default='coach', max_length=30)),
                ('favorite_analysis_type', models.CharField(blank=True, max_length=80)),
                ('bio', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
    ]
