# Generated by Django 6.0.7 on 2026-07-13 12:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_country_code',
            field=models.CharField(choices=[('+30', 'Greece (+30)'), ('+357', 'Cyprus (+357)'), ('+44', 'United Kingdom (+44)'), ('+1', 'United States / Canada (+1)'), ('+49', 'Germany (+49)'), ('+33', 'France (+33)'), ('+39', 'Italy (+39)'), ('+34', 'Spain (+34)')], default='+30', max_length=6),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='profile',
            name='organization',
            field=models.CharField(blank=True, help_text='Club, academy, school, or company name.', max_length=25),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Enter 6 to 15 numbers without spaces or symbols.', regex='^[0-9]{6,15}$')]),
        ),
    ]
