# Generated by Django 6.0.6 on 2026-07-06 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='catalogue.category')),
            ],
            options={
                'verbose_name_plural': 'sub-categories',
                'ordering': ['category__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=170, unique=True)),
                ('short_description', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('analysis_type', models.CharField(choices=[('tracking', 'Tracking'), ('heatmap', 'Heatmap'), ('scouting', 'Scouting'), ('tactical', 'Tactical'), ('detection', 'Detection'), ('performance', 'Performance'), ('highlight', 'Highlight'), ('team_shape', 'Team Shape')], max_length=30)),
                ('skill_level', models.CharField(choices=[('amateur', 'Amateur'), ('academy', 'Academy'), ('semi_pro', 'Semi-Pro'), ('professional', 'Professional')], max_length=30)),
                ('video_type', models.CharField(choices=[('full_match', 'Full Match'), ('training', 'Training'), ('player_clips', 'Player Clips')], max_length=30)),
                ('delivery_time', models.CharField(choices=[('24h', '24 Hours'), ('48h', '48 Hours'), ('3_5_days', '3-5 Days')], max_length=30)),
                ('output_format', models.CharField(choices=[('pdf_report', 'PDF Report'), ('dashboard', 'Dashboard'), ('video_overlay', 'Video Overlay'), ('csv_data', 'CSV Data')], max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='catalogue.category')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='catalogue.subcategory')),
            ],
            options={
                'ordering': ['category__name', 'name'],
            },
        ),
        migrations.AddConstraint(
            model_name='subcategory',
            constraint=models.UniqueConstraint(fields=('category', 'slug'), name='unique_subcategory_slug_per_category'),
        ),
    ]
